springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  error:
    include-message: always
#  port: 8081
#  servlet:
#    context-path: /api/v1

app:
  subapp:
    myvar: testVar

spring:
  datasource:

#    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:medicalSystem}?serverTimezone=UTC
#    username: ${DB_USERNAME:root}
#    password: ${DB_PASSWORD:root1945}
    url: jdbc:mysql://dbtest.cb4gewgqsi2f.eu-north-1.rds.amazonaws.com:3306/dbtest
    username: ${DB_USERNAME:dbadmin}
    password: ${DB_PASSWORD:dbadmin1945}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
