
name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Resolve unmet dependencies
        run: sudo apt-get -f install
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t uliana1945/medicalsystemapi .
      - name: Publish image to docker hub
        run: docker push uliana1945/medicalsystemapi:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull uliana1945/medicalsystemapi:latest
      - name: Delete old container
        run: docker rm -f medicalSystemApi-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name medicalSystemApi-container uliana1945/medicalsystemapi